# Generated by Django 4.0.3 on 2022-04-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=30)),
                ('profile_photo', models.ImageField(default='1', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='1', upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=30)),
                ('likes', models.IntegerField()),
                ('comments', models.CharField(max_length=30)),
                ('profile', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='insta.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
