# Generated by Django 3.1.7 on 2022-04-02 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0007_auto_20220402_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='image_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
