# Generated by Django 3.1.7 on 2022-04-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20220402_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='user',
        ),
    ]
