# Generated by Django 3.1.7 on 2022-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_auto_20220403_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
